name: Protect Grass

on:
  schedule:
    - cron: "30 15 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@v1.0
        with:
          timezone: Asia/Seoul
      - uses: actions/checkout@v2
      - name: Set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm ci
      - name: Update history.log
        run: npm run commit
      - name: Commit files
        run: |
          git config --local user.name "${{ secrets.USER_NAME }}"
          git config --local user.email "${{ secrets.USER_EMAIL }}"
          git add history.log
          git commit -m "Protected Grass"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
